# Generated by Django 4.2.2 on 2023-06-23 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
